'use strict';

var plugins = [
  require('remark-lint'),
	// require('remark-validate-links'),
	[require('remark-lint-blockquote-indentation'), ['error', 2]],
	[require('remark-lint-checkbox-character-style'), ['warn']],
	[require('remark-lint-checkbox-content-indent'), ['error']],
	[require('remark-lint-code-block-style'), ['error', 'fenced']],
	// [require('remark-lint-definition-case'), ['off']],
	[require('remark-lint-definition-spacing'), ['error']],
	[require('remark-lint-emphasis-marker'), ['error', '_']],
	[require('remark-lint-fenced-code-flag'), ['error']],
	[require('remark-lint-fenced-code-marker'), ['error', '`']],
	[require('remark-lint-file-extension'), ['error']],
	[require('remark-lint-final-definition'), ['error']],
	//	[require('remark-lint-final-newline'), ['off']],
	[require('remark-lint-first-heading-level'), ['warn', 1]],
	// [require('remark-lint-hard-break-spaces'), ['off']],
	[require('remark-lint-heading-increment'), ['error']],
	[require('remark-lint-heading-style'), ['error', 'atx']],
	[require('remark-lint-link-title-style'), ['warn', '"']],
	[require('remark-lint-list-item-bullet-indent'), ['error']],
	[require('remark-lint-list-item-content-indent'), ['warn']],
	[require('remark-lint-list-item-indent'), ['error', 'space']],
	// [require('remark-lint-list-item-spacing'), ['off']],
	// [require('remark-lint-maximum-heading-length'), ['off']],
	// [require('remark-lint-maximum-line-length', ['off']],
	[require('remark-lint-no-auto-link-without-protocol'), ['error']],
	[require('remark-lint-no-blockquote-without-marker'), ['error']],
	[require('remark-lint-no-consecutive-blank-lines'), ['error']],
	[require('remark-lint-no-duplicate-definitions'), ['error']],
	// [require('remark-lint-no-duplicate-headings'), ['off']],
	[require('remark-lint-no-duplicate-headings-in-section'), ['error']],
	[require('remark-lint-no-emphasis-as-heading'), ['error']],
	[require('remark-lint-no-empty-url'), ['error']],
	// [require('remark-lint-no-file-name-articles'), ['off']],
	// [require('remark-lint-no-file-name-consecutive-dashes'), ['off']],
	[require('remark-lint-no-file-name-irregular-characters'), ['warn', '\\.a-zA-Z0-9-_']],
	[require('remark-lint-no-file-name-mixed-case'), ['error']],
	[require('remark-lint-no-file-name-outer-dashes'), ['error']],
	[require('remark-lint-no-heading-content-indent'), ['error']],
	[require('remark-lint-no-heading-indent'), ['error']],
	[require('remark-lint-no-heading-like-paragraph'), ['error']],
	// [require('remark-lint-no-heading-punctuation'), ['off']],
	// [require('remark-lint-no-html'), ['off']],
	[require('remark-lint-no-inline-padding'), ['error']],
	// [require('remark-lint-no-literal-urls'), ['off']],
	// [require('remark-lint-no-missing-blank-lines'), ['off']],
	[require('remark-lint-no-multiple-toplevel-headings'), ['error']],
	[require('remark-lint-no-reference-like-url'), ['error']],
	[require('remark-lint-no-shell-dollars'), ['error']],
	// [require('remark-lint-no-shortcut-reference-image'), ['off']],
	// [require('remark-lint-no-shortcut-reference-link'), ['off']],
	[require('remark-lint-no-table-indentation'), ['error']],
	[require('remark-lint-no-tabs'), ['error']],
	[require('remark-lint-no-undefined-references'), ['error']],
	[require('remark-lint-no-unused-definitions'), ['error']],
	[require('remark-lint-ordered-list-marker-style'), ['error', '.']],
	[require('remark-lint-ordered-list-marker-value'), ['error', 'one']],
	[require('remark-lint-rule-style'), ['error', '***']],
	[require('remark-lint-strong-marker'), ['error', '*']],
	[require('remark-lint-table-cell-padding'), ['warn', 'padded']],
	[require('remark-lint-table-pipe-alignment'), ['warn']],
	[require('remark-lint-table-pipes'), ['warn']],
	[require('remark-lint-unordered-list-marker-style'), ['warn', '*']]
];

module.exports.plugins = plugins;
